# -*- coding: utf-8 -*-
"""Pillar5_Step2_DataGeneration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1omyKnnoQt1XlMIAhviayaPAZ4XXe6XtV
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# ---- CONFIG ----
num_records = 5000
devices = ["R1","R2","R3"] + \
          [f"SW{i}" for i in range(1,11)] + \
          [f"APP{i}" for i in range(1,16)] + \
          [f"DB{i}" for i in range(1,6)] + \
          [f"FW{i}" for i in range(1,4)]
data = []
start_time = datetime.now()

for i in range(num_records):
    timestamp = start_time + timedelta(minutes=i)
    host = random.choice(devices)

    # Base values (normal behaviour)
    traffic_in = np.random.normal(80, 20)
    traffic_out = np.random.normal(75, 18)
    latency_ms = np.random.normal(25, 10)
    packet_loss = abs(np.random.normal(0.5, 0.2))

    # Decide if this row is anomalous
    anomaly = 1 if random.random() < 0.08 else 0

    if anomaly:
        traffic_in *= np.random.randint(2, 8)
        traffic_out *= np.random.randint(2, 6)
        latency_ms *= np.random.randint(2, 10)
        packet_loss = min(packet_loss * 5, 100)

        # Label logic (service state)
        service_state = np.select(
            [
                latency_ms > 120,
                packet_loss > 30,
                traffic_in > 300
            ],
            [2, 2, 1],   # 2 = Critical, 1 = Warning
            default=3     # Unknown
        )
    else:
        service_state = 0  # Normal / OK

    data.append([timestamp, host, traffic_in, traffic_out, latency_ms, packet_loss, service_state, anomaly])

df = pd.DataFrame(data, columns=[
    "timestamp","host","traffic_in","traffic_out",
    "latency_ms","packet_loss","service_state","anomaly_flag"
])

df.to_csv("nagios_network_traffic.csv", index=False)
print("DONE: nagios_network_traffic.csv generated!")
print(df.head())